gobcrack.exe /p AVT.FNT AVT.UNP
gobcrack.exe /p JEUDAK.FNT JEUDAK.UNP
gobcrack.exe /p JEULET1.FNT JEULET1.UNP
gobcrack.exe /p JEULET2.FNT JEULET2.UNP
gobcrack.exe /p MAJ1.FNT MAJ1.UNP
gobcrack.exe /p MAJ2.FNT MAJ2.UNP
gobcrack.exe /p MAJ3.FNT MAJ3.UNP
gobcrack.exe /l AVT.UNP AVT.LET
gobcrack.exe /l JEUDAK.UNP JEUDAK.LET
gobcrack.exe /l JEULET1.UNP JEULET1.LET
gobcrack.exe /l JEULET2.UNP JEULET2.LET
gobcrack.exe /l MAJ1.UNP MAJ1.LET
gobcrack.exe /l MAJ2.UNP MAJ2.LET
gobcrack.exe /l MAJ3.UNP MAJ3.LET 