gobcrack.exe /u EMA1.LET EMA1.UNP
gobcrack.exe /u EMA2.LET EMA2.UNP
gobcrack.exe /u EMA3.LET EMA3.UNP
gobcrack.exe /u EMA4.LET EMA4.UNP
gobcrack.exe /u EMA5.LET EMA5.UNP
gobcrack.exe /u EMA6.LET EMA6.UNP
gobcrack.exe /u PROFECY.LET PROFECY.UNP
gobcrack.exe /f EMA1.UNP EMA1.FNT
gobcrack.exe /f EMA2.UNP EMA2.FNT
gobcrack.exe /f EMA3.UNP EMA3.FNT
gobcrack.exe /f EMA4.UNP EMA4.FNT
gobcrack.exe /f EMA5.UNP EMA5.FNT
gobcrack.exe /f EMA6.UNP EMA6.FNT
gobcrack.exe /f PROFECY.UNP PROFECY.FNT