gobcrack.exe /p J1.FNT J1.UNP
gobcrack.exe /p J3.FNT J3.UNP
gobcrack.exe /p JEUCAR1.FNT JEUCAR1.UNP
gobcrack.exe /p JEULET0.FNT JEULET0.UNP
gobcrack.exe /p PROTECT.FNT PROTECT.UNP
gobcrack.exe /l J1.UNP J1.LET
gobcrack.exe /l J3.UNP J3.LET
gobcrack.exe /l JEUCAR1.UNP JEUCAR1.LET
gobcrack.exe /l JEULET0.UNP JEULET0.LET
gobcrack.exe /l PROTECT.UNP PROTECT.LET	 