gobcrack.exe /u J1.LET J1.UNP
gobcrack.exe /u J3.LET J3.UNP
gobcrack.exe /u JEUCAR1.LET JEUCAR1.UNP
gobcrack.exe /u JEULET0.LET JEULET0.UNP
gobcrack.exe /u PROTECT.LET PROTECT.UNP
gobcrack.exe /f J1.UNP J1.FNT
gobcrack.exe /f J3.UNP J3.FNT
gobcrack.exe /f JEUCAR1.UNP JEUCAR1.FNT
gobcrack.exe /f JEULET0.UNP JEULET0.FNT
gobcrack.exe /f PROTECT.UNP PROTECT.FNT	 