gobcrack.exe /u AVT.LET AVT.UNP
gobcrack.exe /u JEUDAK.LET JEUDAK.UNP
gobcrack.exe /u JEULET1.LET JEULET1.UNP
gobcrack.exe /u JEULET2.LET JEULET2.UNP
gobcrack.exe /u MAJ1.LET MAJ1.UNP
gobcrack.exe /u MAJ2.LET MAJ2.UNP
gobcrack.exe /u MAJ3.LET MAJ3.UNP
gobcrack.exe /f AVT.UNP AVT.FNT
gobcrack.exe /f JEUDAK.UNP JEUDAK.FNT
gobcrack.exe /f JEULET1.UNP JEULET1.FNT
gobcrack.exe /f JEULET2.UNP JEULET2.FNT
gobcrack.exe /f MAJ1.UNP MAJ1.FNT
gobcrack.exe /f MAJ2.UNP MAJ2.FNT
gobcrack.exe /f MAJ3.UNP MAJ3.FNT