gobcrack.exe /p EMA1.FNT EMA1.UNP
gobcrack.exe /p EMA2.FNT EMA2.UNP
gobcrack.exe /p EMA3.FNT EMA3.UNP
gobcrack.exe /p EMA4.FNT EMA4.UNP
gobcrack.exe /p EMA5.FNT EMA5.UNP
gobcrack.exe /p EMA6.FNT EMA6.UNP
gobcrack.exe /p PROFECY.FNT PROFECY.UNP
gobcrack.exe /l EMA1.UNP EMA1.LET
gobcrack.exe /l EMA2.UNP EMA2.LET
gobcrack.exe /l EMA3.UNP EMA3.LET
gobcrack.exe /l EMA4.UNP EMA4.LET
gobcrack.exe /l EMA5.UNP EMA5.LET
gobcrack.exe /l EMA6.UNP EMA6.LET
gobcrack.exe /l PROFECY.UNP PROFECY.LET